/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JsConsoleMirror {
    }
}
declare global {
    interface HTMLJsConsoleMirrorElement extends Components.JsConsoleMirror, HTMLStencilElement {
    }
    var HTMLJsConsoleMirrorElement: {
        prototype: HTMLJsConsoleMirrorElement;
        new (): HTMLJsConsoleMirrorElement;
    };
    interface HTMLElementTagNameMap {
        "js-console-mirror": HTMLJsConsoleMirrorElement;
    }
}
declare namespace LocalJSX {
    interface JsConsoleMirror {
    }
    interface IntrinsicElements {
        "js-console-mirror": JsConsoleMirror;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "js-console-mirror": LocalJSX.JsConsoleMirror & JSXBase.HTMLAttributes<HTMLJsConsoleMirrorElement>;
        }
    }
}
